### ISSUE TITLE
Sign up - passwordless option does not register account

### ISSUE THREAD

**Issue by seb-kw** [l3montree-dev/devguard-web#89]
It was tried to sign up a new account with passwordless option. All details were given. After the passkey was confirmed on device side the form reset, but no account was created. 

![Screenshot 2024-11-13 at 11 29 02](https://github.com/user-attachments/assets/3a75b28d-93e7-4eba-b85b-d7867e695fc4)

**Comment by refoo0** [comment]
![Uploading Bildschirmfoto 2024-11-25 um 13.14.10.png…]()

**Comment by seb-kw** [comment]
Fixed - Great, thank you and get a Hax!
